compile:
	@rm -f asheninka.bin
	@foma -f asheninka.script
	@echo "#########################################"
	@echo "  RANDOM MORPHOLOGICAL ANALYSIS TESTING  "
	@echo "#########################################"
	@printf "iquenquitsatacota\nnonkibero\nnochenko\nnovito\nnoyoka\n\
iraantsi\n\
iraani\n\
iraani" > text.txt
	@cat text.txt | flookup asheninka.bin
	@rm -f text.txt
	@echo "#########################################"
	@echo "LENITION MORPHOLOGICAL ANALYSIS TESTING  "
	@echo "#########################################"
	@printf "pitotsi\nnovito\npivito\nivito\novito\navito\n\
pava\nnovavani\npivavani\nivavani\novavani\navavani\n\
koka\nnoyokani\npiyokani\niyokani\nyokani\nyokani\n\
kaniri\nnoyaniri\npiyaniri\niyaniri\nyaniri\nyaniri\n\
kami\nnoyamini\npiyamini\niyamini\nyamini\nyamini" > text.txt
	@cat text.txt | flookup asheninka.bin
	@rm -f text.txt
	@printf "kitsarentsi\nnoitsari\npiitsari\niitsari\noitsari\naitsari\n\
kitzitsi\nnoitzi\npiitzi\niitzi\noitzi\naitzi\n\
kishitsi\nnoishi\npiishi\niishi\noishi\naishi\n\
kipatsi\nnoipatsite\npiipatsite\niipatsite\noipatsite\naipatsite\n\
kitsoki\nnoitsoki\npiitsoki\niitsoki\noitsoki\naitsoki" > text.txt
	@cat text.txt | flookup asheninka.bin
	@rm -f text.txt

#iraantsi\n\ # blood
#iraani\n\ # her.blood
#iraani\n\ # blood
