# Copyright (c) 1999, 2000, 2005 Xerox Corporation.  All Rights Reserved.

aymara.ps: aymara.vcg clean
	xvcg -blackwhite  -psoutput aymara.ps -landscape -split 25 aymara.vcg

clean:
	rm -f aymara.ps


# -split 4
# -psoutput aymara.ps
# -scale 75

# for vcg
# -paper a4 
# -landscape  
